# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='user_profile',
        ),
    ]
