# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20170301_1346'),
        ('show', '0002_remove_show_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='user',
        ),
        migrations.AddField(
            model_name='show',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile'),
        ),
    ]
