# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='地址')),
                ('birthday', models.DateTimeField(blank=True, db_index=True, help_text='', null=True, verbose_name='生日')),
                ('interest', models.CharField(blank=True, max_length=20, verbose_name='爱好')),
                ('weight', models.IntegerField(blank=True, default=150, verbose_name='体重')),
                ('height', models.IntegerField(blank=True, default=150, verbose_name='身高')),
                ('constellate', models.CharField(blank=True, choices=[('1', '白羊座'), ('2', '金牛座'), ('3', '双子座'), ('4', '巨蟹座'), ('5', '狮子座'), ('6', '处女座'), ('7', '天秤座'), ('8', '天蝎座'), ('9', '射手座'), ('10', '摩羯座'), ('11', '双鱼座'), ('12', '双鱼座')], max_length=10, verbose_name='星座')),
                ('job', models.CharField(blank=True, max_length=10, verbose_name='职业')),
                ('movie_type', models.CharField(blank=True, max_length=10, verbose_name='电影类型')),
                ('sport_type', models.CharField(blank=True, max_length=10, verbose_name='运动爱好')),
                ('book_type', models.CharField(blank=True, max_length=10, verbose_name='书籍类型')),
                ('karma', models.IntegerField(default=0, editable=False)),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('following', models.ManyToManyField(blank=True, related_name='_profile_following_+', to='user_profile.Profile')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='user_profile.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='show')),
                ('comments', models.CharField(blank=True, max_length=10, verbose_name='说明')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_profile.Profile')),
            ],
        ),
    ]
