# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='user_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, db_index=True, help_text='', null=True, verbose_name='生日'),
        ),
    ]
