# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20170304_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, db_index=True, help_text='', null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='show'),
        ),
    ]
