# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_auto_20170306_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='company',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='company',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
