# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_auto_20170305_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubinfo',
            options={'verbose_name': 'GitHub项目', 'verbose_name_plural': 'GitHub项目'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': '技术栈', 'verbose_name_plural': '技术栈'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='content',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=10, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='job',
            name='cities',
            field=models.CharField(blank=True, max_length=10, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='job',
            name='province',
            field=models.CharField(blank=True, max_length=10, verbose_name='省'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_end',
            field=models.IntegerField(blank=True, default=0, verbose_name='待遇（到）'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_start',
            field=models.IntegerField(blank=True, default=0, verbose_name='待遇（始）'),
        ),
        migrations.AddField(
            model_name='job',
            name='zone',
            field=models.CharField(blank=True, max_length=10, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50, verbose_name='一行介绍'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='hot',
            field=models.IntegerField(blank=True, verbose_name='热度'),
        ),
    ]
