# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0004_auto_20170306_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stack.Job'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stack.Stack'),
        ),
    ]
