# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0005_auto_20170306_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='hot',
            field=models.IntegerField(blank=True, null=True, verbose_name='热度'),
        ),
    ]
