# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0006_auto_20170306_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
