# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0008_auto_20170307_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.RemoveField(
            model_name='stack',
            name='category',
        ),
        migrations.AddField(
            model_name='stack',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='stack', to='stack.Category', verbose_name='分类'),
        ),
    ]
