# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0009_auto_20170307_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='jobs',
        ),
        migrations.AddField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='stack', to='stack.Job', verbose_name='相关工作'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='stacks',
        ),
        migrations.AddField(
            model_name='company',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='company', to='stack.Stack', verbose_name='技术栈'),
        ),
    ]
