# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0011_auto_20170307_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='company', to='stack.Job', verbose_name='相关工作'),
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='current_stack',
        ),
        migrations.AddField(
            model_name='programmer',
            name='current_stack',
            field=models.ManyToManyField(blank=True, related_name='current_stack', to='stack.Stack', verbose_name='当前技术栈'),
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='future_stack',
        ),
        migrations.AddField(
            model_name='programmer',
            name='future_stack',
            field=models.ManyToManyField(blank=True, related_name='future_stack', to='stack.Stack', verbose_name='公司'),
        ),
    ]
