# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0012_auto_20170307_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='stack.Job', verbose_name='相关工作'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='stacks', to='stack.Stack', verbose_name='技术栈'),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='company', to='stack.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='stack.Category', verbose_name='分类'),
        ),
    ]
