# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0013_auto_20170307_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='future_stack',
            field=models.ManyToManyField(blank=True, related_name='future_stack', to='stack.Stack', verbose_name='未来技术栈'),
        ),
    ]
