# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0014_auto_20170307_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='used_stacks', to='stack.Stack', verbose_name='技术栈'),
        ),
    ]
