# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 12:43
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0015_job_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='stack'),
        ),
    ]
