# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0016_stack_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
