# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0017_job_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='company_stacks', to='stack.Stack', verbose_name='技术栈'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='job_stacks', to='stack.Stack', verbose_name='技术栈'),
        ),
    ]
