# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(default='https://www.phodal.com/'),
        ),
    ]
